
package com.bizvpm.windchill;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TegWCServiceService", targetNamespace = "http://demo.ws.bizvpm.com/", wsdlLocation = "http://127.0.0.1:8080/windchillservice/TegWCService?wsdl")
public class TegWCServiceService
    extends Service
{

    private final static URL TEGWCSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TEGWCSERVICESERVICE_EXCEPTION;
    private final static QName TEGWCSERVICESERVICE_QNAME = new QName("http://demo.ws.bizvpm.com/", "TegWCServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/windchillservice/TegWCService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEGWCSERVICESERVICE_WSDL_LOCATION = url;
        TEGWCSERVICESERVICE_EXCEPTION = e;
    }

    public TegWCServiceService() {
        super(__getWsdlLocation(), TEGWCSERVICESERVICE_QNAME);
    }

    public TegWCServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEGWCSERVICESERVICE_QNAME, features);
    }

    public TegWCServiceService(URL wsdlLocation) {
        super(wsdlLocation, TEGWCSERVICESERVICE_QNAME);
    }

    public TegWCServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEGWCSERVICESERVICE_QNAME, features);
    }

    public TegWCServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TegWCServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TegWCService
     */
    @WebEndpoint(name = "TegWCServicePort")
    public TegWCService getTegWCServicePort() {
        return super.getPort(new QName("http://demo.ws.bizvpm.com/", "TegWCServicePort"), TegWCService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TegWCService
     */
    @WebEndpoint(name = "TegWCServicePort")
    public TegWCService getTegWCServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.ws.bizvpm.com/", "TegWCServicePort"), TegWCService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEGWCSERVICESERVICE_EXCEPTION!= null) {
            throw TEGWCSERVICESERVICE_EXCEPTION;
        }
        return TEGWCSERVICESERVICE_WSDL_LOCATION;
    }

}
