
package com.bizvpm.windchill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TegWCService", targetNamespace = "http://demo.ws.bizvpm.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TegWCService {


    /**
     * 
     * @param ouidList
     * @return
     *     returns com.bizvpm.windchill.DataObject
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByOuidListRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByOuidListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByOuidList/Fault/Exception")
    })
    public DataObject getWTPartBasicInfoByOuidList(
        @WebParam(name = "ouidList", partName = "ouidList")
        DataObject ouidList)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docOuid
     * @return
     *     returns com.bizvpm.windchill.DataSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getDocDetailInfoByOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getDocDetailInfoByOuidResponse")
    public DataSet getDocDetailInfoByOuid(
        @WebParam(name = "docOuid", partName = "docOuid")
        String docOuid);

    /**
     * 
     * @param epmOuid
     * @return
     *     returns com.bizvpm.windchill.DataSet
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getEPMDetailInfoByOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getEPMDetailInfoByOuidResponse")
    public DataSet getEPMDetailInfoByOuid(
        @WebParam(name = "epmOuid", partName = "epmOuid")
        String epmOuid);

    /**
     * 
     * @param partOuid
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getDescribeLinkDocByPartOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getDescribeLinkDocByPartOuidResponse")
    public DataObject getDescribeLinkDocByPartOuid(
        @WebParam(name = "partOuid", partName = "partOuid")
        String partOuid);

    /**
     * 
     * @param partOuid
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getEPMLinkDocByPartOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getEPMLinkDocByPartOuidResponse")
    public DataObject getEPMLinkDocByPartOuid(
        @WebParam(name = "partOuid", partName = "partOuid")
        String partOuid);

    /**
     * 
     * @param linkOuid
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getAlternatesByPartOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getAlternatesByPartOuidResponse")
    public DataObject getAlternatesByPartOuid(
        @WebParam(name = "linkOuid", partName = "linkOuid")
        String linkOuid);

    /**
     * 
     * @param linkOuid
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getSubstituteByLinkOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getSubstituteByLinkOuidResponse")
    public DataObject getSubstituteByLinkOuid(
        @WebParam(name = "linkOuid", partName = "linkOuid")
        String linkOuid);

    /**
     * 
     * @param partOuidList
     * @param linkAttrList
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getBomByOuidListRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getBomByOuidListResponse")
    public DataObject getBomByOuidList(
        @WebParam(name = "partOuidList", partName = "partOuidList")
        DataObject partOuidList,
        @WebParam(name = "linkAttrList", partName = "linkAttrList")
        DataObject linkAttrList);

    /**
     * 
     * @param partOuid
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getUsedPartCountRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getUsedPartCountResponse")
    public int getUsedPartCount(
        @WebParam(name = "partOuid", partName = "partOuid")
        String partOuid);

    /**
     * 
     * @param numberList
     * @return
     *     returns com.bizvpm.windchill.DataObject
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByNumberListRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByNumberListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://demo.ws.bizvpm.com/TegWCService/getWTPartBasicInfoByNumberList/Fault/Exception")
    })
    public DataObject getWTPartBasicInfoByNumberList(
        @WebParam(name = "numberList", partName = "numberList")
        DataObject numberList)
        throws Exception_Exception
    ;

    /**
     * 
     * @param numberList
     * @param attrList
     * @return
     *     returns com.bizvpm.windchill.DataObject
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByNumberListRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByNumberListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByNumberList/Fault/Exception")
    })
    public DataObject getWTPartDetailInfoByNumberList(
        @WebParam(name = "numberList", partName = "numberList")
        DataObject numberList,
        @WebParam(name = "attrList", partName = "attrList")
        DataObject attrList)
        throws Exception_Exception
    ;

    /**
     * 
     * @param ouidList
     * @return
     *     returns com.bizvpm.windchill.DataObject
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByOuidListRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByOuidListResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://demo.ws.bizvpm.com/TegWCService/getWTPartDetailInfoByOuidList/Fault/Exception")
    })
    public DataObject getWTPartDetailInfoByOuidList(
        @WebParam(name = "ouidList", partName = "ouidList")
        DataObject ouidList)
        throws Exception_Exception
    ;

    /**
     * 
     * @param partOuid
     * @return
     *     returns com.bizvpm.windchill.DataObject
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.ws.bizvpm.com/TegWCService/getReferenceLinkDocByPartOuidRequest", output = "http://demo.ws.bizvpm.com/TegWCService/getReferenceLinkDocByPartOuidResponse")
    public DataObject getReferenceLinkDocByPartOuid(
        @WebParam(name = "partOuid", partName = "partOuid")
        String partOuid);

}
